apiVersion: v1
appVersion: v2.11.2-ls53
description: Usenet meta search
name: nzbhydra2
version: 2.0.3
keywords:
  - nzbhydra2
  - usenet
home: https://github.com/billimek/billimek-charts/tree/master/charts/nzbhydra2
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/hydra-icon.png
sources:
  - https://hub.docker.com/r/linuxserver/hydra2/
  - https://github.com/theotherp/nzbhydra2
maintainers:
  - name: billimek
    email: jeff@billimek.com
