apiVersion: v1
appVersion: 3.0.4958-ls73
description: Want a Movie or TV Show on Plex or Emby? Use Ombi!
name: ombi
version: 2.0.3
keywords:
  - ombi
  - plex
home: https://github.com/billimek/billimek-charts/tree/master/charts/ombi
icon: https://ombi.io/img/logo-orange-small.png
sources:
  - https://hub.docker.com/r/linuxserver/ombi/
  - https://ombi.io/
maintainers:
  - name: billimek
    email: jeff@billimek.com
